Transform: AWS::Serverless-2016-10-31
Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      CodeUri: ./
      Policies:
       - AmazonDynamoDBFullAccess
       - AmazonS3FullAccess
       - AWSCodePipeline_FullAccess
      MemorySize: 128
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /test
            Method: get     
